services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: packing_service
      POSTGRES_USER: packing_user
      POSTGRES_PASSWORD: packing_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U packing_user -d packing_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  packing-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=config.yaml
    volumes:
      - ./config.yaml:/root/config.yaml
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: