version: '3.8'

services:
  packing-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=config.yaml
    volumes:
      - ./config.yaml:/root/config.yaml
    restart: unless-stopped